# Generated by Django 5.0.4 on 2024-10-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_userprofile_address_alter_userprofile_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='noofpeople',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
