# Generated by Django 5.0.4 on 2024-10-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userprofile_noofpeople'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile1',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='noofpeople',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='oldorinf',
            field=models.CharField(max_length=100),
        ),
    ]
