# Generated by Django 5.0.4 on 2024-10-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_usermessage_medicalpurpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalpurpose',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='medicalpurpose',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
