# Generated by Django 5.0.4 on 2024-10-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_medicalpurpose_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpurpose',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalpurpose',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
