# Generated by Django 5.0.4 on 2024-10-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_medicalpurpose_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalpurpose',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
